// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb9a-NovfAJ2Ev3_rLTBm4KnY181lE9MI',
    appId: '1:574226202093:web:31749212cee31666463be4',
    messagingSenderId: '574226202093',
    projectId: 'notes-a0987',
    authDomain: 'notes-a0987.firebaseapp.com',
    storageBucket: 'notes-a0987.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrbyu2Z7OgALDJTma0I_9JLFbnjPc9n34',
    appId: '1:574226202093:android:cdf481b9c863b9ae463be4',
    messagingSenderId: '574226202093',
    projectId: 'notes-a0987',
    storageBucket: 'notes-a0987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KztITwVsLiiStqdmWOQycSORlfoeZtY',
    appId: '1:574226202093:ios:edf2b4ae9ec991fd463be4',
    messagingSenderId: '574226202093',
    projectId: 'notes-a0987',
    storageBucket: 'notes-a0987.appspot.com',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1KztITwVsLiiStqdmWOQycSORlfoeZtY',
    appId: '1:574226202093:ios:faca623acaaf4061463be4',
    messagingSenderId: '574226202093',
    projectId: 'notes-a0987',
    storageBucket: 'notes-a0987.appspot.com',
    iosBundleId: 'com.example.firebaseNotes.RunnerTests',
  );
}
